import { useState, useEffect } from 'react'

function useVideos() {
  const [videos, setVideos] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    const timer = setTimeout(() => {
      try {
        setVideos([
          {
            id: '1',
            title: 'Clair Obscur',
            director: 'Jane Doe',
            cast: ['Ben Starr', 'Jenniffer English', 'Charlie Cox'],
            genres: ['Drama', 'Thriller'],
            year: 2023,
            duration: '1h 45min',
            reviews: [
              "Hermosa cinematografía.",
              "Una obra maestra de la luz y sombra.",
            ],
            synopsis: 'Una hermosa película de claroscuros.',
            language: 'Francés',
            thumbnail: 'https://img.youtube.com/vi/K8Tikj_0Cqw/0.jpg',
            url: 'https://www.youtube.com/watch?v=K8Tikj_0Cqw',
          },
          {
            id: '2',
            title: 'Terminator 2: Judgment Day',
            director: 'James Cameron',
            cast: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong'],
            genres: ['Acción', 'Ciencia Ficción', ],
            year: 1998,
            duration: '2h 17min',
            reviews: [
              "Secuela épica de ciencia ficción.",
              "Una de las mejores películas de acción de todos los tiempos.",
            ],
            synopsis: 'Una secuela épica de ciencia ficción.',
            language: 'Inglés',
            thumbnail: 'https://img.youtube.com/vi/nGrW-OR2uDk/0.jpg',
            url: 'https://www.youtube.com/watch?v=nGrW-OR2uDk',
          },
          {
            id: '3',
            title: 'Inception',
            director: 'Christopher Nolan',
            cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
            genres: ['Ciencia Ficción', 'Romance', 'Thriller'],
            year: 2010,
            duration: '2h 28min',
            reviews: [
              "Una película que desafía la mente.",
              "Un viaje alucinante a través de los sueños.",
            ],
            synopsis: 'Un thriller psicológico que juega con la realidad.',
            language: 'Inglés',
            thumbnail: 'https://filmartgallery.com/cdn/shop/files/Inception-Vintage-Movie-Poster-Original.jpg?height=1024&v=1738912645&width=1024',
            url: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
          },
          {
            id: '4',
            title: 'The Matrix',
            director: 'Lana Wachowski, Lilly Wachowski',
            cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
            genres: ['Acción', 'Ciencia Ficción', 'Romance'],
            year: 1999,
            duration: '2h 16min',
            reviews: [
              "Un clásico de la ciencia ficción.",
              "Una película que redefine el género.",
            ],
            synopsis: 'Un hacker descubre la verdad sobre su realidad.',
            language: 'Inglés',
            thumbnail: 'https://filmartgallery.com/cdn/shop/products/The-Matrix-Vintage-Movie-Poster-Original.jpg?v=1738903563',
            url: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
          },
          {
            id: '5',
            title: 'Interstellar',
            director: 'Christopher Nolan',
            cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
            genres: ['Aventura', 'Ciencia Ficción', ],
            year: 2014,
            duration: '2h 49min',
            reviews: [
              "Una obra maestra visual y emocional.",
              "Un viaje épico a través del espacio y el tiempo.",
            ],
            synopsis: 'Un grupo de exploradores viaja a través de un agujero de gusano.',
            language: 'Inglés',
            thumbnail: 'https://film-grab.com/wp-content/uploads/2015/04/35-512.jpg',
            url: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
          },
          {
            id: '6',
            title: 'The Shawshank Redemption',
            director: 'Frank Darabont',
            cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
            genres: ['Drama'],
            year: 1994,
            duration: '2h 22min',
            reviews: [
              "Una historia de esperanza y amistad.",
              "Una película que toca el corazón.",
            ],
            synopsis: 'La historia de un hombre encarcelado injustamente.',
            language: 'Inglés',
            thumbnail: 'https://img.youtube.com/vi/6hB3S9bIaco/0.jpg',
            url: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
          },
          {
            id: '7',
            title: 'The Godfather',
            director: 'Francis Ford Coppola',
            cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
            genres: ['Crimen', 'Drama'],
            year: 1972,
            duration: '2h 55min',
            reviews: [
              "Un clásico del cine.",
              "Una obra maestra de la mafia.",
            ],
            synopsis: 'La historia de una familia mafiosa en Nueva York.',
            language: 'Inglés',
            thumbnail: 'https://img.youtube.com/vi/sY1S34973zA/0.jpg',
            url: 'https://www.youtube.com/watch?v=sY1S34973zA',
          },
          {
            id: '8',
            title: 'Pulp Fiction',
            director: 'Quentin Tarantino',
            cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
            genres: ['Crimen', 'Drama'],
            year: 1994,
            duration: '2h 34min',
            reviews: [
              "Una película innovadora y entretenida.",
              "Un clásico de culto.",
            ],
            synopsis: 'Una serie de historias entrelazadas en Los Ángeles.',
            language: 'Inglés',
            thumbnail: 'https://img.youtube.com/vi/s7EdQ4FqbhY/0.jpg',
            url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
          },
          {
            id: '9',
            title: 'The Dark Knight',
            director: 'Christopher Nolan',
            cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
            genres: ['Acción', 'Crimen'],
            year: 2008,
            duration: '2h 32min',
            reviews: [
              "Una de las mejores películas de superhéroes.",
              "Una actuación inolvidable de Heath Ledger.",
            ],
            synopsis: 'Batman enfrenta al Joker en Gotham City.',
            language: 'Inglés',
            thumbnail: 'https://m.media-amazon.com/images/I/81IfoBox2TL.jpg',
            url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
          },
          {
            id: '10',
            title: 'Forrest Gump',
            director: 'Robert Zemeckis',
            cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
            genres: ['Comedia', 'Drama', 'Romance', ],
            year: 1994,
            duration: '2h 22min',
            reviews: [
              "Una historia conmovedora y divertida.",
              "Una película que deja huella.",
            ],
            synopsis: 'La vida extraordinaria de un hombre común.',
            language: 'Inglés',
            thumbnail: 'https://img.youtube.com/vi/bLvqoHBptjg/0.jpg',
            url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
          },
          {
            id: '11',
            title: 'Gladiator',
            director: 'Ridley Scott',
            cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
            genres: ['Acción', 'Aventura'],
            year: 2000,
            duration: '2h 35min',
            reviews: [
              "Una épica historia de venganza.",
              "Una película visualmente impresionante.",
            ],
            synopsis: 'Un general romano se convierte en gladiador.',
            language: 'Inglés',
            thumbnail: 'https://img.youtube.com/vi/owK1qxDselE/0.jpg',
            url: 'https://www.youtube.com/watch?v=owK1qxDselE',
          },
          {
            id: '12',
            title: 'The Silence of the Lambs',
            director: 'Jonathan Demme',
            cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
            genres: ['Crimen', 'Thriller', ],
            year: 1991,
            duration: '1h 58min',
            reviews: [
              "Un thriller psicológico inquietante.",
              "Una actuación magistral de Anthony Hopkins.",
            ],
            synopsis: 'Una joven agente del FBI busca la ayuda de un asesino encarcelado.',
            language: 'Inglés',
            thumbnail: 'https://m.media-amazon.com/images/I/61o-mUgN++L._AC_SY879_.jpg',
            url: 'https://www.youtube.com/watch?v=6iB21hsprAQ',
          },
          {
            id: '13',
            title: 'The Lord of the Rings: The Fellowship of the Ring',
            director: 'Peter Jackson',
            cast: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'],
            genres: ['Aventura', 'Fantasía'],
            year: 2001,
            duration: '2h 58min',
            reviews: [
              "Una adaptación épica de la obra maestra de Tolkien.",
              "Un viaje inolvidable a la Tierra Media.",
            ],
            synopsis: 'Un grupo de héroes se embarca en una misión para destruir un anillo poderoso.',
            language: 'Inglés',
            thumbnail: 'https://m.media-amazon.com/images/I/81EBp0vOZZL.jpg',
            url: 'https://www.youtube.com/watch?v=V75dMMIW2B4',
          },
          {
            id: '14',
            title: 'Fight Club',
            director: 'David Fincher',
            cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
            genres: ['Drama', 'Thriller'],
            year: 1999,
            duration: '2h 19min',
            reviews: [
              "Una película provocadora y controvertida.",
              "Una crítica a la sociedad de consumo.",
            ],
            synopsis: 'Un hombre insatisfecho con su vida forma un club de lucha clandestino.',
            language: 'Inglés',
            thumbnail: 'https://m.media-amazon.com/images/I/81D+KJkO4SL.jpg',
            url: 'https://www.youtube.com/watch?v=qtRKdVHc-cE',
          },
          {
            id: '15',
            title: 'The Social Network',
            director: 'David Fincher',
            cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
            genres: ['Drama'],
            year: 2010,
            duration: '2h 00min',
            reviews: [
              "Una mirada fascinante a la creación de Facebook.",
              "Una historia de ambición y traición.",
            ],
            synopsis: 'La historia de la creación de Facebook y sus controversias.',
            language: 'Inglés',
            thumbnail: 'https://m.media-amazon.com/images/M/MV5BMjlkNTE5ZTUtNGEwNy00MGVhLThmZjMtZjU1NDE5Zjk1NDZkXkEyXkFqcGc@._V1_.jpg',
            url: 'https://www.youtube.com/watch?v=lB95KLmpLR4',
          },
          {
            id: '16',
            title: 'The Grand Budapest Hotel',
            director: 'Wes Anderson',
            cast: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric'],
            genres: ['Aventura', 'Comedia',],
            year: 2014,
            duration: '1h 39min',
            reviews: [
              "Una comedia visualmente deslumbrante.",
              "Una historia encantadora y divertida.",
            ],
            synopsis: 'Las aventuras de un conserje de hotel y su aprendiz.',
            language: 'Inglés',
            thumbnail: 'https://m.media-amazon.com/images/I/713kiC-8JhL._UF894,1000_QL80_.jpg',
            url: 'https://www.youtube.com/watch?v=1Fg5iWmQjwk',
          },
          {
            id: '17',
            title: 'Parasite',
            director: 'Bong Joon-ho',
            cast: ['Kang-ho Song', 'Sun-kyun Lee', 'Yeo-jeong Jo'],
            genres: ['Drama', 'Thriller'],
            year: 2019,
            duration: '2h 12min',
            reviews: [
              "Una crítica social brillante y entretenida.",
              "Una película que desafía las expectativas.",
            ],
            synopsis: 'La historia de dos familias de clases sociales opuestas.',
            language: 'Inglés',
            thumbnail: 'https://assets.mubicdn.net/images/notebook/post_images/29833/images-w1400.jpg?1579571205',
            url: 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
          },
          {
            id: '18',
            title: 'Spirited Away',
            director: 'Hayao Miyazaki',
            cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
            genres: ['Animación', 'Fantasía'],
            year: 2001,
            duration: '2h 5min',
            reviews: [
              "Una obra maestra de la animación japonesa.",
              "Una historia mágica y conmovedora.",
            ],
            synopsis: 'Una niña se pierde en un mundo espiritual y debe encontrar su camino a casa.',
            language: 'Japonés',
            thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMs5tcwSdrUL1B5zpHs-d696v1MiiQoWt8wA&s',
            url: 'https://www.youtube.com/watch?v=ByXuk9QqQkk',
          },
          {
            id: '19',
            title: 'The Lion King',
            director: 'Roger Allers, Rob Minkoff',
            cast: ['Matthew Broderick', 'James Earl Jones', 'Jeremy Irons'],
            genres: ['Animación', 'Aventura', 'Comedia', 'Drama', ],
            year: 1994,
            duration: '1h 28min',
            reviews: [
              "Un clásico de Disney que toca el corazón.",
              "Una historia de crecimiento y redención.",
            ],
            synopsis: 'La historia de un joven león que debe reclamar su lugar como rey.',
            language: 'Inglés',
            thumbnail: 'https://img.youtube.com/vi/4sj1MT05lAA/0.jpg',
            url: 'https://www.youtube.com/watch?v=4sj1MT05lAA',
          },
          {
            id: '20',
            title: 'Back to the Future',
            director: 'Robert Zemeckis',
            cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
            genres: ['Aventura', 'Ciencia Ficción', ],
            year: 1985,
            duration: '1h 56min',
            reviews: [
              "Una aventura atemporal llena de diversión.",
              "Un clásico de la ciencia ficción.",
            ],
            synopsis: 'Un adolescente viaja al pasado y debe asegurarse de que sus padres se conozcan.',
            language: 'Inglés',
            thumbnail: 'https://wallpapers.com/images/hd/back-to-the-future-1-movie-poster-3lt7w0va9gflvj87.jpg',
            url: 'https://www.youtube.com/watch?v=qvsgGtivCgs',
          },
            {
            id: '21',
            title: 'The Avengers',
            director: 'Joss Whedon',
            cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
            genres: ['Acción', 'Aventura', 'Ciencia Ficción'],
            year: 2012,
            duration: '2h 23min',
            reviews: [
              "Un crossover épico de superhéroes.",
              "Una película llena de acción y humor.",
            ],
            synopsis: 'Un grupo de superhéroes se une para salvar el mundo.',
            language: 'Inglés',
            thumbnail: 'https://wallpapers.com/images/featured/avengers-vm16xv4a69smdauy.jpg',
            url: 'https://www.youtube.com/watch?v=eOrNdBpGMv8',
            }
        ])
        setLoading(false)
      } catch (err) {
        setError(err)
        setLoading(false)
      }
    }, 1500)

    return () => clearTimeout(timer)
  }, [])

  return { videos, loading, error }
}

export default useVideos